"""
Shikshak AI — Visual Selection & Dispatch Router.

Single responsibility:
  1. Validate visual modes across scenes generated by Scene Planning.
  2. Dispatch scene rendering to the matching domain renderer
     (reaction_lab, equation_build, experiment_observation, balancing_exercise, generic_explainer).
  3. Maintain backward compatibility with legacy segment-level planning.
"""
from __future__ import annotations

import re
from pathlib import Path
from typing import Any, Callable

from celery_app import celery_app
from skills.scene_renderers import RENDERER_REGISTRY, get_scene_renderer


def select_visuals(plan: dict[str, Any]) -> dict[str, Any]:
    """Walk every segment and scene, verifying that visual modes are valid
    and ready for dispatch. Falls back gracefully for legacy segments."""
    new_segments = []
    for s in plan.get("segments", []):
        s = dict(s)
        # If segment has structured scenes, validate their visual modes
        if s.get("scenes"):
            for sc in s["scenes"]:
                mode = sc.get("visual_mode")
                if mode not in RENDERER_REGISTRY:
                    sc["visual_mode"] = "generic_explainer"
        
        # Legacy visual_type check
        if s.get("visual_type") == "none" or not s.get("visual_type"):
            s["visual_type"] = _infer_legacy_visual_type(s.get("concept", ""))
        new_segments.append(s)

    new_plan = dict(plan)
    new_plan["segments"] = new_segments
    return new_plan


def get_renderer_for_mode(visual_mode: str) -> Callable[..., Path]:
    """Retrieve the render function for a visual mode."""
    return get_scene_renderer(visual_mode)


def dispatch_scene_render(
    scene: dict[str, Any],
    duration_seconds: float = 6.0,
    out_path: Path | None = None,
) -> Path:
    """Render a single scene using its configured visual_mode renderer."""
    mode = scene.get("visual_mode", "generic_explainer")
    renderer = get_scene_renderer(mode)
    payload = scene.get("visual_payload") or {}
    narration = scene.get("narration_text") or ""
    return renderer(
        payload_dict=payload,
        narration_text=narration,
        duration_seconds=duration_seconds,
        out_path=out_path,
    )


def _infer_legacy_visual_type(concept: str) -> str:
    """Legacy helper for non-scene callers."""
    c = concept.lower()
    # Molecular structures (Hydrocarbons, functional groups, Carbon compounds)
    if re.search(r"\b(methane|ethane|ethanol|ethanoic acid|ethyne|alkane|alkene|alkyne|hydrocarbon|molecular structure|covalent bond|chemical bond|isomer|ester)\b", c):
        return "molecular_structure"
    # Circuit diagrams (Ohm's law, circuits, resistors)
    if re.search(r"\b(circuit|resistor|resistance|ohm's law|ammeter|voltmeter|series circuit|parallel circuit|electric current)\b", c):
        return "circuit_diagram"
    # Curated biological illustrations
    if re.search(r"\b(heart|neuron|flower|plant cell|animal cell|eye\b|nephron|dna\b|double helix|chloroplast|photosynthesis structure)\b", c):
        return "bio_illustration"
    if re.search(r"\bequation\b|\bformula\b|\bintegral\b|\bderivative\b|\bsolve\b", c):
        return "equation"
    if re.search(r"\bcode\b|\bfunction\b|\bloop\b|\brecursion\b|\bvariable\b|\bclass\b", c):
        return "code"
    if re.search(r"\bdiagram\b|\bflow\b|\bstructure\b|\bcycle\b|\bprocess\b", c):
        return "diagram"
    if re.search(r"\bmotion\b|\bwave\b|\bkinetic\b|\bdynamic\b|\banimate\b", c):
        return "animation"
    return "none"


# Alias for backward compatibility with legacy tests
_infer_visual_type = _infer_legacy_visual_type



@celery_app.task(name="agents.visual_selection.run")
def run(plan: dict[str, Any]) -> dict[str, Any]:
    return select_visuals(plan)
