-- 012_add_diagram_spec_columns.sql
-- Shikshak AI — Add pre-computed diagram spec columns to lesson_segments
--
-- These columns store the animation specification generated alongside the
-- narration script by the content_scriptwriter agent. This eliminates the
-- need for LLM calls during the render pipeline — the animation is fully
-- deterministic once these fields are populated.

-- Pre-computed DiagramSpec (nodes, edges, layout, title, formula)
-- Generated by content_scriptwriter during the explanation step
alter table lesson_segments
  add column if not exists diagram_spec_json jsonb;

-- Per-scene animation breakdown (narration_text + visual_nodes per scene)
alter table lesson_segments
  add column if not exists animation_scenes_json jsonb;

-- Related concepts for deep-dive navigation
-- (moved from inline plan dict to persisted column)
alter table lesson_segments
  add column if not exists related_concepts jsonb;

comment on column lesson_segments.diagram_spec_json is
  'Pre-computed DiagramSpec from content_scriptwriter — used at render time instead of LLM call';

comment on column lesson_segments.animation_scenes_json is
  'Per-scene animation breakdown with matched narration + visual elements';

comment on column lesson_segments.related_concepts is
  'Related sub-topics for deep-dive navigation';
